# Generated by Django 3.1.1 on 2020-10-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('srl', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.IntegerField(blank=True, null=True)),
                ('mesaageTitle', models.CharField(max_length=500)),
                ('messageBody', models.CharField(max_length=1000)),
            ],
        ),
    ]
