# Generated by Django 3.1.1 on 2020-10-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('TECHNOLOGY', 'tech'), ('PYTHON', 'py'), ('JAVA SCRIPT', 'js')], max_length=50),
        ),
    ]
