# Generated by Django 3.1.1 on 2020-10-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20201019_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('TECHNOLOGY', 'tech'), ('PYTHON', 'py'), ('JAVA SCRIPT', 'js'), ('JAVA', 'java')], max_length=50),
        ),
    ]
