# Generated by Django 3.1.1 on 2020-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20201019_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clickRate',
            field=models.IntegerField(default=0),
        ),
    ]
