# Generated by Django 3.1.1 on 2020-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_post_clickrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('srl', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, choices=[('TECHNOLOGY', 'tech'), ('PYTHON', 'py'), ('JAVA SCRIPT', 'js'), ('JAVA', 'java')], max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='default_image_cat.jpg', upload_to='')),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image_post.jpg', upload_to=''),
        ),
    ]
