# Generated by Django 3.1.2 on 2020-10-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20201021_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('TECHNOLOGY', 'tech'), ('PYTHON', 'py'), ('JAVA SCRIPT', 'js'), ('JAVA', 'java')], max_length=50),
        ),
    ]
