# Generated by Django 3.1.2 on 2020-10-21 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20201021_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('TECHNOLOGY', 'tech'), ('PYTHON', 'py'), ('JAVA SCRIPT', 'js'), ('JAVA', 'java')], max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('image', models.ImageField(default='default_image_auth.jpg', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myblog.author'),
        ),
    ]
