# Generated by Django 3.1.2 on 2020-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20201021_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
